# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Brix Labs
email: bonjour@brixlabs.ca
description: >- # this means to ignore newlines until "baseurl:"
  Brix Labs - Spécialiste des données. Brix Labs offre des produits et des services qui
  aident les entreprises, en particulier les entreprises culturelles, à tirer
  profit du numérique pour commercialiser leurs offres. Elle se spécialise dans
  les approches qui s’appuient sur la création ou l’utilisation de données.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.brixlabs.ca" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  jekyll # TODO
slogan: Spécialiste des données
keywords: données, métadonnées, transformation organisationnelle, numérique, science des données
company_name: Brix Labs

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
paginate: 4
paginate_path: "blog/page:num"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
